# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cmr_spec": "00_Default_Model.ipynb",
         "DefaultCMR": "00_Default_Model.ipynb",
         "encoding_states": "01_Visualizing_Model_States.ipynb",
         "plot_states": "01_Visualizing_Model_States.ipynb",
         "encoding_visualizations": "01_Visualizing_Model_States.ipynb",
         "retrieval_states": "01_Visualizing_Model_States.ipynb",
         "outcome_probs_at_index": "01_Visualizing_Model_States.ipynb",
         "retrieval_visualizations": "01_Visualizing_Model_States.ipynb",
         "prepare_murddata": "02_Data_Preparation.ipynb",
         "prepare_repdata": "02_Data_Preparation.ipynb",
         "simulate_data": "02_Data_Preparation.ipynb",
         "visualize_individuals": "03_Benchmark_Analyses.ipynb",
         "visualize_aggregate": "03_Benchmark_Analyses.ipynb",
         "visualize_model": "03_Benchmark_Analyses.ipynb",
         "visualize_fit": "03_Benchmark_Analyses.ipynb",
         "recall_probability_by_lag": "04_Repetition_Effects.ipynb",
         "sim_recall_probability_by_lag": "04_Repetition_Effects.ipynb",
         "cmr_rep_likelihood": "05_Fitting_By_Likelihood.ipynb",
         "cmr_rep_objective_function": "05_Fitting_By_Likelihood.ipynb",
         "cmr_rep_mse": "06_Fitting_By_MSE.ipynb",
         "cmr_rep_mse_objective_function": "06_Fitting_By_MSE.ipynb"}

modules = ["models.py",
           "model_analysis.py",
           "datasets.py",
           "model_fitting.py"]

doc_url = "https://Solve-Memory.github.io/repfr/"

git_url = "https://github.com/Solve-Memory/repfr/tree/{branch}/"

def custom_doc_links(name): return None
